---
title: "Prevalence of chronic pain in the US (2012)"
author: "Peter Kamerman"
date: "05 September 2015"
output: 
    md_document:
        variant: markdown_github
---
Prevalence of chronic pain in the US (2012)
===========================================

Summary
-------


Data analysis
-------------
### Data entry and simulation
```{r data, echo = TRUE, warning = FALSE, message  = FALSE, tidy = TRUE, tidy.opts = list(width.cutoff = 75)}
# Total sample from the 2012 NHIS Adult Functioning and Disability Supplement (AFD)
# No pain: 
NoPain <- 3663
# Pain some days:
SomeDays <- 3258
# Pain most days:
MostDays <- 553
# Pain every day: 
EveryDay <- 992
# Pain on most/every day:
MostEvery <- MostDays + EveryDay
# Total sample
Total <- sum(NoPain, SomeDays, MostDays, EveryDay)
Total
# Proportion with pain every day within the last 3 months
EveryDay.P <- EveryDay / Total
EveryDay.P
# Proportion with pain most days within the last 3 months
MostDays.P <- MostDays / Total
MostDays.P
# Proportion with pain on most or every day within the last 3 months
MostEvery.P <- MostEvery / Total
MostEvery.P
# Simulations
## Create dataset 
Sim <- data.frame(EveryDay = factor(c(rep('Other', Total-EveryDay), 
                                    rep('Chronic pain', EveryDay)),
                                    levels = c('Other', 'Chronic pain'), 
                                    labels = c('Other', 'Chronic pain')),
                  MostDays = factor(c(rep('Other', Total-MostDays), 
                                    rep('Pain on most days', MostDays)),
                                    levels = c('Other', 'Pain on most days'), 
                                    labels = c('Other', 'Pain on most days')),
                  MostEvery = factor(c(rep('Other', Total-MostEvery), 
                                        rep('Pain on most.every day', MostEvery)),
                                    levels = c('Other', 'Pain on most.every day'), 
                                    labels = c('Other', 'Pain on most.every day')))
# 'Top-and-tail' dataset
head(Sim)
tail(Sim)
str(Sim)
## Summarise data
library(pander)
pander(table(Sim$EveryDay), 
       caption = 'Pain every day with the last 3 months (chronic pain)',
       justify = 'left', type = 'rmarkdown')
pander(table(Sim$MostDays), 
       caption = 'Pain most days with the last 3 months',
       justify = 'left', type = 'rmarkdown')
pander(table(Sim$MostEvery), 
       caption = 'Pain most or every day with the last 3 months',
       justify = 'left', type = 'rmarkdown')
```

### Bootstrap prevalence and 95% confidence interval
```{r boot, echo = TRUE, warning = FALSE, message  = FALSE, tidy = TRUE, tidy.opts = list(width.cutoff = 75)}
## Bootstrap mean and 95%CI
library(boot)
### Write function to calculate prevalence using bootstrap sample
prev<-function(d,i) {
    dat <- d[i, ]
    tab <- table(dat)
    num <- tab[[2]]
    den <- tab[[1]] + tab[[2]]
    prev <- num / den
    prev
}
### Split the dataframe
EveryDay.1 <- data.frame(Sim[,1])
MostDays.1 <- data.frame(Sim[,2])
MostEvery.1 <- data.frame(Sim[,3])
### Run boot with 10 000 reps
#### Pain every day within the last 3 months
EveryDay.boot<-boot(EveryDay.1, prev, 10000)
plot(EveryDay.boot)
EveryDay.boot
EveryDay.bootci <- boot.ci(EveryDay.boot, conf = 0.95, type = 'basic')
EveryDay.bootci
#### Pain on most days within the last 3 months
MostDays.boot<-boot(MostDays.1, prev, 10000)
plot(MostDays.boot)
MostDays.boot
MostDays.bootci <- boot.ci(MostDays.boot, conf = 0.95, type = 'basic')
MostDays.bootci
#### Pain on most or every day within the last 3 months
MostEvery.boot<-boot(MostEvery.1, prev, 10000)
plot(MostEvery.boot)
MostEvery.boot
MostEvery.bootci <- boot.ci(MostEvery.boot, conf = 0.95, type = 'basic')
MostEvery.bootci
```

### Summary plot
```{r boot.ci, echo = TRUE, warning = FALSE, message  = FALSE, tidy = TRUE, tidy.opts = list(width.cutoff = 75)}
# Make dataset for plotting
plotD <- data.frame(Group = c('Every day', 'Most days', 'Most or every day'),
                    Mean = c(100*EveryDay.boot$t0, 100*MostDays.boot$t0, 100*MostEvery.boot$t0),
                    LowerCI = c(100*EveryDay.bootci$basic[4], 100*MostDays.bootci$basic[4], 100*MostEvery.bootci$basic[4]),
                    UpperCI = c(100*EveryDay.bootci$basic[5], 100*MostDays.bootci$basic[5], 100*MostEvery.bootci$basic[5]),
                    RangeCI = c(100*EveryDay.bootci$basic[5] - 100*EveryDay.bootci$basic[4],
                                100*MostDays.bootci$basic[5] - 100*MostDays.bootci$basic[4], 100*MostEvery.bootci$basic[5] - 100*MostEvery.bootci$basic[4]))
## View dataset
pander(plotD, caption = 'Summary (mean and bootstrap 95%CI) of pain frequency within the last 3 months',
       justify = 'left', 
       type = 'rmarkdown')
## Plot data
library(ggplot2)
library(grid)
library(scales)
library(ggthemes)
# Make a three-colour colourblind palette
cbpalette <- tableau_color_pal('colorblind10')(4)
cbpalette <- cbpalette[-3]
gg.5 <- ggplot(plotD, aes(x = Group, y = Mean, colour = Group)) +
    geom_point(size = 5) +
    geom_errorbar(aes(ymin = LowerCI, ymax = UpperCI), width = 0.3, size = 1) +
    labs(x = 'Frequency of pain\nwithin the last 3 months', y = 'Mean (95%CI) prevalence (%)') +
    scale_y_continuous(limits = c(0,20), expand = c(0,0)) +
    scale_colour_manual(values = cbpalette) +
    theme(legend.position = 'none',
          axis.text = element_text(size=16, colour='black'),
          axis.title.x = element_text(size=18, colour='black', face='bold', vjust=0),
          axis.title.y = element_text(size=18, colour='black', face='bold', vjust=1))
gg.5
```

### Session information
```{r session, echo = TRUE, warning = FALSE, message  = FALSE, tidy = TRUE, tidy.opts = list(width.cutoff = 75)}
sessionInfo()
```
